#!/bin/bash


if [ $# -ne 1 ]; then
	echo "Syntax: $0 lv_mapper"
	echo "Example: $0 /dev/mapper/6YD218JT-joe--backup--host"
	exit 1
fi

readonly mapper_lv=$1

echo ${mapper_lv} | sed 's%--%-%g' | sed 's%/dev/mapper/\([a-zA-Z0-9]*\)-\([a-zA-Z0-9-]*\)%/dev/\1/\2%g'`

