#!/bin/bash

# Split a network resource in two

[ -z "${sysman_scripts_dir}" ] && readonly sysman_scripts_dir=$(dirname $0)/..
readonly nas_scripts_dir=${sysman_scripts_dir}/nas

readonly syntax_error=1

print_usage(){
    echo "Split a netrsc in two"
    echo "Syntax:"
    echo "   $0 -p netrsc_path"
    echo "Example:"
    echo "   $0 -p /nas/backup/joe/bigdir" 
    exit ${syntax_error}  
}

if [ "$#" -ge 1 ]; then
    while getopts "p:h" options; do
	case "${options}" in
	    p)
		readonly dir_to_extract="${OPTARG}"
		;;
	    h)
		print_usage
		;;
	esac
    done
else
    print_usage
fi

[ -z "${dir_to_extract}" ] && print_usage

readonly size=$(du -hs ${dir_to_extract} | awk '{print $1}')
readonly vg=$(${nas_scripts_dir}/suggest_vg ${size} | head -1)
readonly parent_lv_mapper=$(df -P ${dir_to_extract | tail -1 | awk '{print $1}')
readonly parent_lv=$(${nas_scripts_dir}/mapper_to_lv ${parent_lv_mapper})
readonly lv_name="$(basename ${parent_lv})-$(basename ${dir_to_extract})"
echo "${nas_scripts_dir}/setup_network_resource -v ${vg} -l ${lv_name} -s ${size} -p ${dir_to_extract}"
echo "Proceed? \( Ctrl-C to cancel \)"
read t

mv ${dir_to_extract} ${dir_to_extract}.orig
${nas_scripts_dir}/setup_network_resource -v ${vg} -l ${lv_name} -s ${size} -p ${dir_to_extract}
rsync -av --progress ${dir_to_extract}.orig/ ${dir_to_extract}/
echo "rm -rf ${dir_to_extract}
