#!/bin/bash

if [ $# -ne 3 ]; then
    echo "Change the names \(volume and mount path\) of a local netrsc"
    echo "Syntax: $0 old_netpath new_netpath new_lv_name"
    echo "Example: $0 /nas/backup/joe /nas/archive/joe joe-archive"
    exit 1
fi

readonly oldnetpath=$1
readonly newnetpath=$2
readonly newlvname=$3

echo "Resource NFS status:"
showmount -a | grep ${oldnetpath}
echo "Press any key to proceed..."
read

escoldnetpath=$(echo ${oldnetpath} | sed 's_/_\\\/_g')
escnewnetpath=$(echo ${newnetpath} | sed 's_/_\\\/_g')
# !!!! Use git?
ci -l -m"rename net resource" -t-exports /etc/exports
sed "s/${escoldnetpath}/${escnewnetpath}/g" -i /etc/exports 
exportfs -a
ci -l  -m"rename net resource" -t-fstab /etc/fstab

readonly lvpath=$(grep ${oldnetpath} /etc/fstab | awk '{print $1}')
readonly baselvpath=$(dirname ${lvpath})
readonly ${newlvpath}="${baselvpath}/${newlvname}"
escoldlvpath=$(echo ${lvpath} | sed 's_/_\\\/_g')
escnewlvpath=$(echo ${newlvpath} | sed 's_/_\\\/_g')

sed "s/${escoldnetpath}/${escnewnetpath}/g" -i /etc/fstab 
sed "s/${escoldlvpath}/${escnewlvpath}/g" -i /etc/fstab 
umount ${oldnetpath}
lvrename ${lvpath} ${newlvpath}
mkdir -p ${newnetpath}
rmdir ${oldnetpath}
mount ${newnetpath}

echo "Remember to update backup config if needed"

