#!/bin/bash

readonly syntax_error=1

print_usage(){
    echo "Change the names (volume and mount path) of a local netrsc"
    echo "Syntax:"
    echo "   $0 -f old_path -t new_path -l new_lv_name"
    echo "Example:"
    echo "   $0 -f /nas/backup/joe -t /nas/archive/joe -l joe-archive"
    exit ${syntax_error}  
}


if [ "$#" -ge 1 ]; then
    while getopts "f:t:l:h" options; do
	case "${options}" in
	    l)
		readonly newlvname=${OPTARG}
		;;
	    f)
		readonly oldnetpath=${OPTARG}
		;;
	    t)
		readonly newnetpath=${OPTARG}
		;;
	    h)
		print_usage
		;;
            *)
		echo "Unknow option" 1>&2 
		print_usage
		;;
	esac
    done
else
    print_usage
fi

[ -z "${oldnetpath}" -o -z "${newnetpath}" -o -z "${newlvname}" ] && print_usage

echo "Resource NFS status:"
showmount -a | grep ${oldnetpath}
echo "Press any key to proceed..."
read

escoldnetpath=$(echo ${oldnetpath} | sed 's_/_\\\/_g')
escnewnetpath=$(echo ${newnetpath} | sed 's_/_\\\/_g')
# !!!! Use git?
ci -l -m"rename net resource" -t-exports /etc/exports
sed "s/${escoldnetpath}/${escnewnetpath}/g" -i /etc/exports 
exportfs -a
ci -l  -m"rename net resource" -t-fstab /etc/fstab

readonly lvpath=$(grep ${oldnetpath} /etc/fstab | awk '{print $1}')
readonly baselvpath=$(dirname ${lvpath})
readonly newlvpath="${baselvpath}/${newlvname}"
escoldlvpath=$(echo ${lvpath} | sed 's_/_\\\/_g')
escnewlvpath=$(echo ${newlvpath} | sed 's_/_\\\/_g')

sed "s/${escoldnetpath}/${escnewnetpath}/g" -i /etc/fstab 
sed "s/${escoldlvpath}/${escnewlvpath}/g" -i /etc/fstab 
umount ${oldnetpath} && \
lvrename ${lvpath} ${newlvpath} && \
mkdir -p ${newnetpath} && \
rmdir ${oldnetpath} && \
mount ${newnetpath} 

echo "Remember to update backup config if needed"

