#!/bin/bash

# !!!! allow more than 1 replica?
[ -z "${sysman_scripts_dir}" ] && readonly sysman_scripts_dir="$(dirname $0)/../.."
[ -z "${SYSMAN_LOGDIR}" ] && readonly SYSMAN_LOGDIR=/var/log
readonly log_file=${SYSMAN_LOGDIR}/nas.log
readonly log_facility="replicas"

. ${sysman_scripts_dir}/misc.sh

# !!!! make replicas_dir & cfg configurable
replica_dir=/nas/replicas
replica_cfg=${SYSMAN_ETC}/replicas/replicas.$(hostname)

if [ $# -ne 2 ]; then
    echo "Syntax: $0 nas_src server vg"
    echo "Example: $0 /nas/joe/work/aa server" 
    exit 1
fi

readonly src=$1
readonly server=$2

grep ${src} ${replica_cfg} > /dev/null
if [ $? -eq 0 ]; then
    echo "There is a replica already - see ${replica_cfg}"
    exit 1
fi

if [ $(hostname) == ${server} ]; then
    echo "replica stored in this same server"
    exit 1
fi

# No / between two because $SRC is absolute...
dst=${server}:${replica_dir}${src}

if [ ! -f ${replica_cfg} ]; then
    echo "Creating ${replica_cfg}"
    ${sysman_scripts_dir}/nas/replicas/replica_create_config ${replica_cfg}
fi

# !!!! Integrate next step into create_replica_config?
echo "${src}/ ${dst} 24 1" >> ${replica_cfg}
