#!/bin/bash

readonly frequency=10
while [ 1 ]; do
    echo "$(date '+%s %Y%m%d %H%M%S') $(nvidia-smi  --query-gpu=pstate,memory.used,utilization.gpu,temperature.gpu --format=csv | tail -n +2 | tr -d '\n')"  >> /var/log/gpu.log
    sleep ${frequency}
done
