#!/bin/bash

readonly data_file=$1

gnuplot <<EOF

set terminal png size 800,800 enhanced font "Helvetica,20"
set ylabel "running threads"
set xdata time
set timefmt "%s"
set format x "%d/%m"
set output 'coss.png'
plot "${data_file}" u 1:2 with lines title "coss"
; pause -1
set output 'melero.png'
plot "${data_file}" u 1:3 with lines title "melero"
; pause -1
set output 'joton.png'
plot "${data_file}" u 1:4 with lines title "joton"
; pause -1
set output 'vahid.png'
plot "${data_file}" u 1:5 with lines title "vahid"
; pause -1
set output 'jvargas.png'
plot "${data_file}" u 1:6 with lines title "jvargas"
; pause -1
set output 'scipion.png'
plot  "${data_file}" u 1:7 with lines title "scipion"
; pause -1
set output 'web.png'
plot "${data_file}" u 1:8 with lines title "web"
; pause -1
set output 'instruct.png'
plot "${data_file}" u 1:9 with lines title "instruct"
; pause -1
set output 'total.png'
plot "${data_file}" u 1:($2+$3+$4+$5+$6+$7+$8+$9) with lines title "total" 
; pause -1
EOF
