#!/bin/bash

readonly docker_path="$(which docker)"

# software installation
if [ -z "${docker_path}" ]; then
    readonly kernel_regex="([0-9]).([0-9]*).*"
    kernel_version_aux=($(uname -v))
    readonly kernel_version=${kernel_version_aux[3]%%~bpo*}
    if [[ "${kernel_version}" =~ ${kernel_regex} ]]; then
	if [ ${BASH_REMATCH[1]} -lt 3 -o ${BASH_REMATCH[2]} -lt 9 ];then
	    echo "Docker requires kernel 3.8 or later. Install it with"
	    echo "apt-get -t wheezy-backports install linux-image-amd64"
	    exit 1
	fi
    else
	apt-get install curl
	curl -sSL https://get.docker.com/ | sh
    fi
fi

# post-install
docker pull ubuntu:14.04
docker images
echo "Next steps:"
echo "- setup the basic container"
echo "  ( mkdir /var/run/sshd if needed)"
echo "docker run -t -i ubuntu:14.04-ssh /bin/bash"
echo "- save the container to the repository"
echo "docker commit ${container-id} ubuntu:14.04-ssh"
