#!/bin/bash

. /etc/san/reports/backup_reports.common

BACKUP_DB=backup


header "Slow backups"

#echo "<table><tr><td>Module</td><td>Avg transfer size (MB)</td><td>Total backup size (MB)</td></tr>"

biocs_query $BACKUP_DB "select  module, round(AVG(size)/(1024*1024)) as size,ttc from backup where datediff(now() ,date) < 7 order by ttc desc LIMIT 10"

#echo "</table>"
