#!/bin/bash
# Update the backup database 
#
BDIR=/etc/sysman/nas_reports/

# . $BDIR/biocs_mysql_query.sh

cat /var/log/rsyncd.log | awk -f /usr/local/sysman/nas/reports/backup_log_to_db.awk | $BDIR/biocs_mysql_query.sh -
